# Generated by Django 2.2.1 on 2019-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('system', 'system'), ('data_store', 'dateStore')], default='system', max_length=20)),
                ('service', models.CharField(choices=[('internal', 'internal'), ('outernal', 'outernal')], default='internal', max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('layer', models.IntegerField(default=1)),
                ('connect_from', models.ManyToManyField(blank=True, null=True, related_name='_system_connect_from_+', to='systems.System', verbose_name='接続元')),
                ('connect_to', models.ManyToManyField(blank=True, null=True, related_name='_system_connect_to_+', to='systems.System', verbose_name='接続先')),
                ('parent_id', models.ManyToManyField(blank=True, null=True, related_name='_system_parent_id_+', to='systems.System', verbose_name='親システム')),
            ],
        ),
    ]
